### ISSUE TITLE
This line is wrong. 

### ISSUE THREAD

**Issue by yifeiwang77** [4uiiurz1/pytorch-auto-augment#2]
It should be ['Solarize', 0.5, 2, 'Invert', 0.0, 3]

https://github.com/4uiiurz1/pytorch-auto-augment/blob/024b2eac4140c38df8342f09998e307234cafc80/auto_augment.py#L25

**Comment by 4uiiurz1** [comment]
@doxawang
Thanks for letting me know.
I fixed it.
