### ISSUE TITLE
CIFAR100: Invalid mean and std

### ISSUE THREAD

**Issue by tgilewicz** [4uiiurz1/pytorch-auto-augment#3]
https://github.com/4uiiurz1/pytorch-auto-augment/blob/024b2eac4140c38df8342f09998e307234cafc80/train.py#L193

It should be:
```
    mean = (0.5071, 0.4867, 0.4408)
    std = (0.2675, 0.2565, 0.2761)
```

**Comment by 4uiiurz1** [comment]
@tgilewicz 
Thanks for letting me know.
I fixed it.
